version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    restart: always

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    restart: always
  
  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - "6379:6379"
    restart: always

  kafka-ui:
    container_name: Kafka-UI
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
      - redis

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    ports:
      - "8001:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: always
    
  producer:
    container_name: producer
    build: ./producer
    depends_on:
      - kafka
      - redis
    restart: always
    environment:
      - KAFKA_BROKER=kafka:9092

  consumer:
    container_name: consumer
    build: ./consumer
    depends_on:
      - kafka
      - redis
    restart: always
    environment:
      - KAFKA_BROKER=kafka:9092

  web:
    container_name: web
    build: ./web
    ports:
      - "5001:5001"
    depends_on:
      - redis
    restart: always
  
